FROM ubuntu:latest

RUN apt update && apt upgrade -y && apt install -y cmake git build-essential autoconf libtool pkg-config libboost-dev

RUN mkdir /src

RUN cd /src && \
    git clone https://github.com/grpc/grpc.git && \
    cd /src/grpc && \
    git submodule update --init --recursive

RUN mkdir -p /src/grpc/cmake/build && cd /src/grpc/cmake/build && cmake -DgRPC_INSTALL=ON /src/grpc && make && make install